
const 
  defaultLanguage = "en",
  supportedLanguages = [
    {"value":"af","name":"Afrikaans"},
    {"value":"af-ZA","name":"Afrikaans (South Africa)"},
    {"value":"am-ET","name":"Amharic (Ethiopia)"},
    {"value":"ar","name":"Arabic"},
    {"value":"ar-AE","name":"Arabic (U.A.E.)"},
    {"value":"ar-BH","name":"Arabic (Bahrain)"},
    {"value":"ar-DZ","name":"Arabic (Algeria)"},
    {"value":"ar-EG","name":"Arabic (Egypt)"},
    {"value":"ar-IQ","name":"Arabic (Iraq)"},
    {"value":"ar-JO","name":"Arabic (Jordan)"},
    {"value":"ar-KW","name":"Arabic (Kuwait)"},
    {"value":"ar-LB","name":"Arabic (Lebanon)"},
    {"value":"ar-LY","name":"Arabic (Libya)"},
    {"value":"ar-MA","name":"Arabic (Morocco)"},
    {"value":"ar-OM","name":"Arabic (Oman)"},
    {"value":"ar-QA","name":"Arabic (Qatar)"},
    {"value":"ar-SA","name":"Arabic (Saudi Arabia)"},
    {"value":"ar-SY","name":"Arabic (Syria)"},
    {"value":"ar-TN","name":"Arabic (Tunisia)"},
    {"value":"ar-YE","name":"Arabic (Yemen)"},
    {"value":"arn-CL","name":"Mapudungun (Chile)"},
    {"value":"as-IN","name":"Assamese (India)"},
    {"value":"az","name":"Azeri"},
    {"value":"az-Cyrl-AZ","name":"Azeri (Cyrillic) (Azerbaijan)"},
    {"value":"az-Latn-AZ","name":"Azeri (Latin) (Azerbaijan)"},
    {"value":"ba-RU","name":"Bashkir (Russia)"},
    {"value":"be","name":"Belarusian"},
    {"value":"be-BY","name":"Belarusian (Belarus)"},
    {"value":"bg","name":"Bulgarian"},
    {"value":"bg-BG","name":"Bulgarian (Bulgaria)"},
    {"value":"bn-BD","name":"Bengali (Bangladesh)"},
    {"value":"bn-IN","name":"Bengali (India)"},
    {"value":"bo-CN","name":"Tibetan (People's Republic of China)"},
    {"value":"br-FR","name":"Breton (France)"},
    {"value":"bs-Cyrl-BA","name":"Bosnian (Cyrillic) (Bosnia and Herzegovina)"},
    {"value":"bs-Latn-BA","name":"Bosnian (Latin) (Bosnia and Herzegovina)"},
    {"value":"ca","name":"Catalan"},
    {"value":"ca-ES","name":"Catalan (Catalan)"},
    {"value":"co-FR","name":"Corsican (France)"},
    {"value":"cs","name":"Czech"},
    {"value":"cs-CZ","name":"Czech (Czech Republic)"},
    {"value":"cy-GB","name":"Welsh (United Kingdom)"},
    {"value":"da","name":"Danish"},
    {"value":"da-DK","name":"Danish (Denmark)"},
    {"value":"de","name":"German"},
    {"value":"de-AT","name":"German (Austria)"},
    {"value":"de-CH","name":"German (Switzerland)"},
    {"value":"de-DE","name":"German (Germany)"},
    {"value":"de-LI","name":"German (Liechtenstein)"},
    {"value":"de-LU","name":"German (Luxembourg)"},
    {"value":"dsb-DE","name":"Lower Sorbian (Germany)"},
    {"value":"dv","name":"Divehi"},
    {"value":"dv-MV","name":"Divehi (Maldives)"},
    {"value":"el","name":"Greek"},
    {"value":"el-GR","name":"Greek (Greece)"},
    {"value":"en","name":"English"},
    {"value":"en-029","name":"English (Caribbean)"},
    {"value":"en-AU","name":"English (Australia)"},
    {"value":"en-BZ","name":"English (Belize)"},
    {"value":"en-CA","name":"English (Canada)"},
    {"value":"en-GB","name":"English (United Kingdom)"},
    {"value":"en-IE","name":"English (Ireland)"},
    {"value":"en-IN","name":"English (India)"},
    {"value":"en-JM","name":"English (Jamaica)"},
    {"value":"en-MY","name":"English (Malaysia)"},
    {"value":"en-NZ","name":"English (New Zealand)"},
    {"value":"en-PH","name":"English (Republic of the Philippines)"},
    {"value":"en-SG","name":"English (Singapore)"},
    {"value":"en-TT","name":"English (Trinidad and Tobago)"},
    {"value":"en-US","name":"English (United States)"},
    {"value":"en-ZA","name":"English (South Africa)"},
    {"value":"en-ZW","name":"English (Zimbabwe)"},
    {"value":"es","name":"Spanish"},
    {"value":"es-AR","name":"Spanish (Argentina)"},
    {"value":"es-BO","name":"Spanish (Bolivia)"},
    {"value":"es-CL","name":"Spanish (Chile)"},
    {"value":"es-CO","name":"Spanish (Colombia)"},
    {"value":"es-CR","name":"Spanish (Costa Rica)"},
    {"value":"es-DO","name":"Spanish (Dominican Republic)"},
    {"value":"es-EC","name":"Spanish (Ecuador)"},
    {"value":"es-ES","name":"Spanish (Spain)"},
    {"value":"es-GT","name":"Spanish (Guatemala)"},
    {"value":"es-HN","name":"Spanish (Honduras)"},
    {"value":"es-LA","name":"Spanish (Latin America)"},
    {"value":"es-MX","name":"Spanish (Mexico)"},
    {"value":"es-NI","name":"Spanish (Nicaragua)"},
    {"value":"es-PA","name":"Spanish (Panama)"},
    {"value":"es-PE","name":"Spanish (Peru)"},
    {"value":"es-PR","name":"Spanish (Puerto Rico)"},
    {"value":"es-PY","name":"Spanish (Paraguay)"},
    {"value":"es-SV","name":"Spanish (El Salvador)"},
    {"value":"es-US","name":"Spanish (United States)"},
    {"value":"es-UY","name":"Spanish (Uruguay)"},
    {"value":"es-VE","name":"Spanish (Venezuela)"},
    {"value":"et","name":"Estonian"},
    {"value":"et-EE","name":"Estonian (Estonia)"},
    {"value":"eu","name":"Basque"},
    {"value":"eu-ES","name":"Basque (Basque)"},
    {"value":"fa","name":"Persian"},
    {"value":"fa-IR","name":"Persian (Iran)"},
    {"value":"fi","name":"Finnish"},
    {"value":"fi-FI","name":"Finnish (Finland)"},
    {"value":"fil-PH","name":"Filipino (Philippines)"},
    {"value":"fo","name":"Faroese"},
    {"value":"fo-FO","name":"Faroese (Faroe Islands)"},
    {"value":"fr","name":"French"},
    {"value":"fr-BE","name":"French (Belgium)"},
    {"value":"fr-CA","name":"French (Canada)"},
    {"value":"fr-CH","name":"French (Switzerland)"},
    {"value":"fr-FR","name":"French (France)"},
    {"value":"fr-LU","name":"French (Luxembourg)"},
    {"value":"fr-MC","name":"French (Principality of Monaco)"},
    {"value":"fy-NL","name":"Frisian (Netherlands)"},
    {"value":"ga-IE","name":"Irish (Ireland)"},
    {"value":"gd-GB","name":"Scottish Gaelic (United Kingdom)"},
    {"value":"gl","name":"Galician"},
    {"value":"gl-ES","name":"Galician (Galician)"},
    {"value":"gsw-FR","name":"Alsatian (France)"},
    {"value":"gu","name":"Gujarati"},
    {"value":"gu-IN","name":"Gujarati (India)"},
    {"value":"ha-Latn-NG","name":"Hausa (Latin) (Nigeria)"},
    {"value":"he","name":"Hebrew"},
    {"value":"he-IL","name":"Hebrew (Israel)"},
    {"value":"hi","name":"Hindi"},
    {"value":"hi-IN","name":"Hindi (India)"},
    {"value":"hr","name":"Croatian"},
    {"value":"hr-BA","name":"Croatian (Latin) (Bosnia and Herzegovina)"},
    {"value":"hr-HR","name":"Croatian (Croatia)"},
    {"value":"hsb-DE","name":"Upper Sorbian (Germany)"},
    {"value":"hu","name":"Hungarian"},
    {"value":"hu-HU","name":"Hungarian (Hungary)"},
    {"value":"hy","name":"Armenian"},
    {"value":"hy-AM","name":"Armenian (Armenia)"},
    {"value":"id","name":"Indonesian"},
    {"value":"id-ID","name":"Indonesian (Indonesia)"},
    {"value":"ig-NG","name":"Igbo (Nigeria)"},
    {"value":"ii-CN","name":"Yi (People's Republic of China)"},
    {"value":"is","name":"Icelandic"},
    {"value":"is-IS","name":"Icelandic (Iceland)"},
    {"value":"it","name":"Italian"},
    {"value":"it-CH","name":"Italian (Switzerland)"},
    {"value":"it-IT","name":"Italian (Italy)"},
    {"value":"iu-Cans-CA","name":"Inuktitut (Syllabics) (Canada)"},
    {"value":"iu-Latn-CA","name":"Inuktitut (Latin) (Canada)"},
    {"value":"ja","name":"Japanese"},
    {"value":"ja-JP","name":"Japanese (Japan)"},
    {"value":"ka","name":"Georgian"},
    {"value":"ka-GE","name":"Georgian (Georgia)"},
    {"value":"kk","name":"Kazakh"},
    {"value":"kk-KZ","name":"Kazakh (Kazakhstan)"},
    {"value":"kl-GL","name":"Greenlandic (Greenland)"},
    {"value":"km-KH","name":"Khmer (Cambodia)"},
    {"value":"kn","name":"Kannada"},
    {"value":"kn-IN","name":"Kannada (India)"},
    {"value":"ko","name":"Korean"},
    {"value":"ko-KR","name":"Korean (Korea)"},
    {"value":"kok","name":"Konkani"},
    {"value":"kok-IN","name":"Konkani (India)"},
    {"value":"ky","name":"Kyrgyz"},
    {"value":"ky-KG","name":"Kyrgyz (Kyrgyzstan)"},
    {"value":"la","name":"Latin"},
    {"value":"lb-LU","name":"Luxembourgish (Luxembourg)"},
    {"value":"lo-LA","name":"Lao (Lao P.D.R.)"},
    {"value":"lt","name":"Lithuanian"},
    {"value":"lt-LT","name":"Lithuanian (Lithuania)"},
    {"value":"lv","name":"Latvian"},
    {"value":"lv-LV","name":"Latvian (Latvia)"},
    {"value":"mi-NZ","name":"Maori (New Zealand)"},
    {"value":"mk","name":"Macedonian"},
    {"value":"mk-MK","name":"Macedonian (Former Yugoslav Republic of Macedonia)"},
    {"value":"ml-IN","name":"Malayalam (India)"},
    {"value":"mn","name":"Mongolian"},
    {"value":"mn-MN","name":"Mongolian (Cyrillic) (Mongolia)"},
    {"value":"mn-Mong-CN","name":"Mongolian (Traditional Mongolian) (People's Republic of China)"},
    {"value":"moh-CA","name":"Mohawk (Canada)"},
    {"value":"mr","name":"Marathi"},
    {"value":"mr-IN","name":"Marathi (India)"},
    {"value":"ms","name":"Malay"},
    {"value":"ms-BN","name":"Malay (Brunei Darussalam)"},
    {"value":"ms-MY","name":"Malay (Malaysia)"},
    {"value":"mt-MT","name":"Maltese (Malta)"},
    {"value":"nb-NO","name":"Norwegian, Bokmål (Norway)"},
    {"value":"ne-NP","name":"Nepali (Nepal)"},
    {"value":"nl","name":"Dutch"},
    {"value":"nl-BE","name":"Dutch (Belgium)"},
    {"value":"nl-NL","name":"Dutch (Netherlands)"},
    {"value":"nn-NO","name":"Norwegian, Nynorsk (Norway)"},
    {"value":"no","name":"Norwegian"},
    {"value":"nso-ZA","name":"Sesotho sa Leboa (South Africa)"},
    {"value":"oc-FR","name":"Occitan (France)"},
    {"value":"or-IN","name":"Oriya (India)"},
    {"value":"pa","name":"Punjabi"},
    {"value":"pa-IN","name":"Punjabi (India)"},
    {"value":"pl","name":"Polish"},
    {"value":"pl-PL","name":"Polish (Poland)"},
    {"value":"prs-AF","name":"Dari (Afghanistan)"},
    {"value":"ps-AF","name":"Pashto (Afghanistan)"},
    {"value":"pt","name":"Portuguese"},
    {"value":"pt-BR","name":"Portuguese (Brazil)"},
    {"value":"pt-PT","name":"Portuguese (Portugal)"},
    {"value":"qut-GT","name":"K'iche (Guatemala)"},
    {"value":"quz-BO","name":"Quechua (Bolivia)"},
    {"value":"quz-EC","name":"Quechua (Ecuador)"},
    {"value":"quz-PE","name":"Quechua (Peru)"},
    {"value":"rm-CH","name":"Romansh (Switzerland)"},
    {"value":"ro","name":"Romanian"},
    {"value":"ro-RO","name":"Romanian (Romania)"},
    {"value":"ru","name":"Russian"},
    {"value":"ru-RU","name":"Russian (Russia)"},
    {"value":"rw-RW","name":"Kinyarwanda (Rwanda)"},
    {"value":"sa","name":"Sanskrit"},
    {"value":"sa-IN","name":"Sanskrit (India)"},
    {"value":"sah-RU","name":"Yakut (Russia)"},
    {"value":"se-FI","name":"Sami (Northern) (Finland)"},
    {"value":"se-NO","name":"Sami (Northern) (Norway)"},
    {"value":"se-SE","name":"Sami (Northern) (Sweden)"},
    {"value":"si-LK","name":"Sinhala (Sri Lanka)"},
    {"value":"sk","name":"Slovak"},
    {"value":"sk-SK","name":"Slovak (Slovakia)"},
    {"value":"sl","name":"Slovenian"},
    {"value":"sl-SI","name":"Slovenian (Slovenia)"},
    {"value":"sma-NO","name":"Sami (Southern) (Norway)"},
    {"value":"sma-SE","name":"Sami (Southern) (Sweden)"},
    {"value":"smj-NO","name":"Sami (Lule) (Norway)"},
    {"value":"smj-SE","name":"Sami (Lule) (Sweden)"},
    {"value":"smn-FI","name":"Sami (Inari) (Finland)"},
    {"value":"sms-FI","name":"Sami (Skolt) (Finland)"},
    {"value":"sq","name":"Albanian"},
    {"value":"sq-AL","name":"Albanian (Albania)"},
    {"value":"sr","name":"Serbian"},
    {"value":"sr-Cyrl-BA","name":"Serbian (Cyrillic) (Bosnia and Herzegovina)"},
    {"value":"sr-Cyrl-CS","name":"Serbian (Cyrillic) (Serbia and Montenegro (Former))"},
    {"value":"sr-Cyrl-ME","name":"Serbian (Cyrillic) (Montenegro)"},
    {"value":"sr-Cyrl-RS","name":"Serbian (Cyrillic) (Serbia)"},
    {"value":"sr-Latn-BA","name":"Serbian (Latin) (Bosnia and Herzegovina)"},
    {"value":"sr-Latn-CS","name":"Serbian (Latin) (Serbia and Montenegro (Former))"},
    {"value":"sr-Latn-ME","name":"Serbian (Latin) (Montenegro)"},
    {"value":"sr-Latn-RS","name":"Serbian (Latin) (Serbia)"},
    {"value":"sv","name":"Swedish"},
    {"value":"sv-FI","name":"Swedish (Finland)"},
    {"value":"sv-SE","name":"Swedish (Sweden)"},
    {"value":"sw","name":"Kiswahili"},
    {"value":"sw-KE","name":"Kiswahili (Kenya)"},
    {"value":"syr","name":"Syriac"},
    {"value":"syr-SY","name":"Syriac (Syria)"},
    {"value":"ta","name":"Tamil"},
    {"value":"ta-IN","name":"Tamil (India)"},
    {"value":"te","name":"Telugu"},
    {"value":"te-IN","name":"Telugu (India)"},
    {"value":"tg-Cyrl-TJ","name":"Tajik (Cyrillic) (Tajikistan)"},
    {"value":"th","name":"Thai"},
    {"value":"th-TH","name":"Thai (Thailand)"},
    {"value":"tk-TM","name":"Turkmen (Turkmenistan)"},
    {"value":"tn-ZA","name":"Setswana (South Africa)"},
    {"value":"tr","name":"Turkish"},
    {"value":"tr-TR","name":"Turkish (Turkey)"},
    {"value":"tt","name":"Tatar"},
    {"value":"tt-RU","name":"Tatar (Russia)"},
    {"value":"tzm-Latn-DZ","name":"Tamazight (Latin) (Algeria)"},
    {"value":"ug-CN","name":"Uyghur (People's Republic of China)"},
    {"value":"uk","name":"Ukrainian"},
    {"value":"uk-UA","name":"Ukrainian (Ukraine)"},
    {"value":"ur","name":"Urdu"},
    {"value":"ur-PK","name":"Urdu (Islamic Republic of Pakistan)"},
    {"value":"uz","name":"Uzbek"},
    {"value":"uz-Cyrl-UZ","name":"Uzbek (Cyrillic) (Uzbekistan)"},
    {"value":"uz-Latn-UZ","name":"Uzbek (Latin) (Uzbekistan)"},
    {"value":"vi","name":"Vietnamese"},
    {"value":"vi-VN","name":"Vietnamese (Vietnam)"},
    {"value":"wo-SN","name":"Wolof (Senegal)"},
    {"value":"xh-ZA","name":"isiXhosa (South Africa)"},
    {"value":"yo-NG","name":"Yoruba (Nigeria)"},
    {"value":"zh-Hans","name":"Chinese (Simplified)"},
    {"value":"zh-Hant","name":"Chinese (Traditional)"},
    {"value":"zh-CN","name":"Chinese (People's Republic of China)"},
    {"value":"zh-HK","name":"Chinese (Hong Kong S.A.R.)"},
    {"value":"zh-MO","name":"Chinese (Macao S.A.R.)"},
    {"value":"zh-SG","name":"Chinese (Singapore)"},
    {"value":"zh-TW","name":"Chinese (Taiwan)"},
    {"value":"zu-ZA","name":"isiZulu (South Africa)"}
  ]


module.exports = {defaultLanguage,supportedLanguages};

